#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on: workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' && github.sha || '' }}
  cancel-in-progress: true

jobs:
  duckdb-stable-build:
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.4-andium
    with:
      duckdb_version: v1.4.4
      ci_tools_version: v1.4-andium
      extension_name: aixchess
      extra_toolchains: rust
      exclude_archs: 'windows_amd64_mingw;wasm_mvp;wasm_eh;wasm_threads'
      opt_in_archs: windows_arm64
